<li>
        <div class="block">
          <div class="pic"><img src="[field:picname/]" alt="[field:title/]"></div>
          <div class="txt"> <a href="[field:arcurl/]" style="width:100%;height:100%;display:block;"> <b></b>
            <div class="pad">
              <h5>[field:typename/]</h5>
              <em></em>
              <h3>[field:title/]</h3>
              <span class="more">案例详情</span> </div>
            </a> </div>
        </div>
      </li>