<li>
          <div class="pad">
            <div class="txt"> <span><em>[field:pubdate function="MyDate('m/d',@me)"/]</em>[field:pubdate function="MyDate('Y',@me)"/]</span>
              <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
              <p>[field:info/]...</p>
              <a href="[field:arcurl/]" class="more"></a> </div>
            <div class="hover">
              <div class="img" style="background: url([field:picname/]) 0 0 /100% 100% no-repeat;background: url([field:picname/]) 0 0 no-repeat\9;"></div>
              <div class="pad">
                <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                <p>[field:info/]...</p>
              </div>
            </div>
          </div>
        </li>