<?php
$z[0]=Array("pubdate","",75,120);
$z[0][4]['function']="MyDate('m/d',@me)";
$z[1]=Array("pubdate","",125,168);
$z[1][4]['function']="MyDate('Y',@me)";
$z[2]=Array("arcurl","",204,219);
$z[3]=Array("title","",221,235);
$z[4]=Array("info","",263,276);
$z[5]=Array("arcurl","",308,323);
$z[6]=Array("picname","",438,454);
$z[7]=Array("picname","",497,513);
$z[8]=Array("arcurl","",603,618);
$z[9]=Array("title","",620,634);
$z[10]=Array("info","",664,677);

?>