<?php
$z[0]=Array("arcurl","",69,84);
$z[1]=Array("picname","",96,112);
$z[2]=Array("title","",119,133);
$z[3]=Array("pubdate","",251,296);
$z[3][4]['function']="MyDate('m/d',@me)";
$z[4]=Array("pubdate","",301,344);
$z[4][4]['function']="MyDate('Y',@me)";
$z[5]=Array("arcurl","",382,397);
$z[6]=Array("title","",399,413);
$z[7]=Array("arcurl","",469,484);
$z[8]=Array("description","",525,575);
$z[8][4]['function']="cn_substr(@me,140)";
$z[9]=Array("arcurl","",650,665);

?>