<li>
        <div class="pad">
          <div class="pic"><a href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]"></a></div>
          <div class="bor">
            <div class="txt">
              <div class="title"> <span><em>[field:pubdate function="MyDate('m/d',@me)"/]</em>[field:pubdate function="MyDate('Y',@me)"/]</span>
                <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
              </div>
              <a href="[field:arcurl/]" style="color:#666;">
              <p>[field:description function='cn_substr(@me,140)'/]...</p>
              </a> </div>
            <div class="more"><a href="[field:arcurl/]" class="r">查看更多 ></a></div>
          </div>
        </div>
      </li>