<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",747,782);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1144,1165);
$z[5][4]['name']="content";
$z[6]=Array("include","",13372,13409);
$z[6][4]['filename']="footer.htm";

?>