<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,173);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",213,264);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",733,768);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",870,899);
$z[5][4]['name']="position";
$z[6]=Array("field","",1158,1177);
$z[6][4]['name']="title";
$z[7]=Array("field","",1209,1227);
$z[7][4]['name']="body";
$z[8]=Array("type","<a href=\"[field:typelink/]\">返回案例列表</a>",1289,1362);
$z[9]=Array("include","",1450,1487);
$z[9][4]['filename']="footer.htm";

?>