<?php
$z[0]=Array("channel","\r\n            <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n            ",1100,1329);
$z[0][4]['type']="son";
$z[0][4]['typeid']="1";
$z[0][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a> </li>";
$z[1]=Array("channel","\r\n            <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n            ",1475,1705);
$z[1][4]['type']="son";
$z[1][4]['typeid']="10";
$z[1][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a> </li>";
$z[2]=Array("global","",2193,2219);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",2309,2333);
$z[3][4]['name']="cfg_beian";

?>