<?php
$z[0]=Array("global","",64,90);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",134,164);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",201,228);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",791,826);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n            <li> <a href=\"[field:arcurl/]\">\r\n              <div class=\"pic\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"></div>\r\n              <div class=\"hover\"> <b></b>\r\n                <div class=\"txt\"> <img src=\"/skin/images/logo_small.png\" alt=\"\">\r\n                  <h3>[field:title/]</h3>\r\n                </div>\r\n              </div>\r\n              </a> </li>\r\n            ",4971,5421);
$z[4][4]['row']="8";
$z[4][4]['titlelen']="32";
$z[4][4]['typeid']="1";
$z[5]=Array("type","<a href=\"[field:typelink/]\"></a>",5515,5581);
$z[5][4]['typeid']="1";
$z[6]=Array("arclist","\r\n        <li>\r\n          <div class=\"pad\">\r\n            <div class=\"txt\"> <span><em>[field:pubdate function=\"MyDate('m/d',@me)\"/]</em>[field:pubdate function=\"MyDate('Y',@me)\"/]</span>\r\n              <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n              <p>[field:info/]...</p>\r\n              <a href=\"[field:arcurl/]\" class=\"more\"></a> </div>\r\n            <div class=\"hover\">\r\n              <div class=\"img\" style=\"background: url([field:picname/]) 0 0 /100% 100% no-repeat;background: url([field:picname/]) 0 0 no-repeat\\9;\"></div>\r\n              <div class=\"pad\">\r\n                <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                <p>[field:info/]...</p>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </li>\r\n        ",5835,6691);
$z[6][4]['row']="4";
$z[6][4]['infolen']="120";
$z[6][4]['titlelen']="32";
$z[6][4]['typeid']="10";
$z[7]=Array("type","<a href=\"[field:typelink/]\">load more</a>",6764,6840);
$z[7][4]['typeid']="10";
$z[8]=Array("include","",8827,8864);
$z[8][4]['filename']="footer.htm";

?>