<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",747,782);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1120,1359);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='mycur'><span>~typename~</span></a></li>";
$z[6]=Array("list","\r\n      <li>\r\n        <div class=\"block\">\r\n          <div class=\"pic\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"></div>\r\n          <div class=\"txt\"> <a href=\"[field:arcurl/]\" style=\"width:100%;height:100%;display:block;\"> <b></b>\r\n            <div class=\"pad\">\r\n              <h5>[field:typename/]</h5>\r\n              <em></em>\r\n              <h3>[field:title/]</h3>\r\n              <span class=\"more\">案例详情</span> </div>\r\n            </a> </div>\r\n        </div>\r\n      </li>\r\n      ",1445,1978);
$z[6][4]['pagesize']="12";
$z[7]=Array("pagelist","",2085,2163);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2270,2307);
$z[8][4]['filename']="footer.htm";

?>