<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-09-20 22:24:55
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-09-21 00:05:01
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-09-21 00:13:26
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-09-21 00:14:52
*/
?>
